# Option 1: Specify a logs bucket
options:
  logging: 'CLOUD_LOGGING_ONLY'

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/nginx-test-01:$SHORT_SHA'
      - '.'

  # Step 2: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'nginx-test-02'
      - '--image'
      - 'gcr.io/$PROJECT_ID/nginx-test-01:$SHORT_SHA'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--port'
      - '80'
timeout: 1200s
images:
  - 'gcr.io/$PROJECT_ID/nginx-test-01:$SHORT_SHA'