# Option 1: Specify a logs bucket
options:
  logging: CLOUD_LOGGING_ONLY


steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/basic-nginx-webpage:$SHORT_SHA'
      - '.'

  # Step 2: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'basic-nginx-webpage'
      - '--image'
      - 'gcr.io/$PROJECT_ID/basic-nginx-webpage:$SHORT_SHA'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
timeout: 1200s
images:
  - 'gcr.io/$PROJECT_ID/basic-nginx-webpage:$SHORT_SHA'